### ISSUE TITLE
GTX 1070 no accepted shares on 144.5 algo

### ISSUE THREAD

**Issue by pauk22** [miniZ-miner/miniZ#9]
the latest working version is 18z3. all subsequent versions on GTX1070 show an abnormally high hashrate, but do not find the shares.

**Comment by miniZ-miner** [comment]
Hi pauk22, thanks for the feedback.
We found the issue, a couple of kernels are broken. We are fixing this for the next release.
Meanwhile, you can add --mode=n (n=1,2,3,7,8,9) for that gpu. You can try one of these kernels for that gpu, the best one will depend on your OCs - likely 2 or 3. --OCX wil not work well, because of the broken kernels.
This should help while we fix this.
Cheers

**Comment by miniZ-miner** [comment]
Hi pauk22,
Please update to latest version v1.9z5b.
It should be working well now.
Thank you for the feedback.
We'll close this issue now.
Cheers
